<?php
namespace Zwei\Context;


class TimerCtx extends CancelCtx
{
    /**
     * @var CancelCtx
     */
    protected $cancelCtx;

    /**
     * @var Time
     */
    protected $deadline;

    public function String()
    {
        return (string) $this . ".WithDeadline(" +
            $this->deadline.String() + " [" +
            $this->deadline->Until($this->deadline).String() + "])";
    }


    public function Done()
    {
        if (!$this->done) {
            $this->checkDeadline();
        }
        return parent::Done(); // TODO: Change the autogenerated stub
    }

    public function Deadline() {
        return [$this->deadline, true];
    }

    public function checkDeadline() {
        $dur = $this->deadline->Until($this->deadline);
        if ( $dur <= 0) {
            $this->err = DeadlineExceeded();
            $this->done = true;
        }
    }

    /**
     * @inheritDoc
     */
    public function Cancel($removeFromParent, \Exception $err)
    {
        $this->done = true;
        $this->err = $err;
        $this->cancelCtx->Cancel($removeFromParent, $err);
        foreach ($this->children as $child) {
            $child->Cancel(false, $err);
        }
        foreach ($this->children as $child) {
            $child->Cancel(false, $err);
        }

        if ($removeFromParent) {
            removeChild($this->cancelCtx->parent, $this);
        }
    }


    public static function newTimerCtx(Context $parent, Time $d)
    {
        $ctx = new static();
        $ctx->cancelCtx = parent::newCancelCtx($parent);
        $ctx->deadline = $d;
        return $ctx;
    }
}
